package com.example.webservices.user;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import org.springframework.stereotype.Component;

import com.example.webservices.user.beans.User;

@Component
public class UserDaoService {

	private static List<User> users=new ArrayList<User>();
	int userCount=3;//this value is generated by db as forgien key in real time
	
	static {
		users.add(new User(1,"Vikky1",new Date()));
		users.add(new User(2,"Vikky2",new Date()));
		users.add(new User(3,"Vikky3",new Date()));
	}
	
	//type of operations we do with this is Service is
	//method to findAll,findOne,save
	
	public List<User> findAll(){
		return users;
	}
	
	public User save(User user) {
		if(user.getId()==null) {
			user.setId(++userCount);
		}
		users.add(user);
		return user;
	}
	
	public User findOne(int id) {
		for(User user:users) {
			if(user.getId()==id) {
				return user;
			}
		}
		return null;
	}
	
	public User delete(int id) {
		Iterator<User> iterator =users.iterator();
		while(iterator.hasNext()) {
			User user=iterator.next();
			if(user.getId()==id) {
				iterator.remove();
				return user;
			}
		}
		return null;
	}
}
